---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  components:
    egressGateways:
      - enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - istio-egressgateway
                  topologyKey: kubernetes.io/hostname
          hpaSpec:
            maxReplicas: 3
            minReplicas: 2
        name: istio-egressgateway
    ingressGateways:
      - enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - istio-ingressgateway
                  topologyKey: kubernetes.io/hostname
          hpaSpec:
            maxReplicas: 3
            minReplicas: 2
          service:
            type: LoadBalancer
        name: istio-ingressgateway
      - enabled: true
        k8s:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - istio-eastwestgateway
                  topologyKey: kubernetes.io/hostname
          hpaSpec:
            maxReplicas: 3
            minReplicas: 2
          service:
            ports:
              - name: status-port
                port: 15021
                targetPort: 15021
              - name: tls
                port: 15443
                targetPort: 15443
              - name: tls-istiod
                port: 15012
                targetPort: 15012
              - name: tls-webhook
                port: 15017
                targetPort: 15017
            type: LoadBalancer
        label:
          app: istio-eastwestgateway
          istio: eastwestgateway
        name: istio-eastwestgateway
    pilot:
      enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - istiod
                topologyKey: kubernetes.io/hostname
        hpaSpec:
          maxReplicas: 3
          minReplicas: 2
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: 'true'
        ISTIO_META_DNS_CAPTURE: 'true'
  profile: default
  values:
    gateways:
      istio-ingressgateway:
        injectionTemplate: gateway
    global:
      meshID: mesh1
      multiCluster:
        clusterName: istio-cluster
      network: ''