---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: REPLACE_VM_APP_NAME-REPLACE_VM_APP_INSTANCE
  namespace: REPLACE_VM_NAMESPACE
  labels:
    app: REPLACE_VM_APP_NAME
    instance-id: REPLACE_VM_APP_INSTANCE
spec:
  address: REPLACE_VM_IPADDRESS
  labels:
    app: REPLACE_VM_APP_NAME
    instance-id: REPLACE_VM_APP_INSTANCE
  serviceAccount: REPLACE_VM_SERVICEACCOUNT